# Vector's API for introspection
[api]
enabled = true
address = "127.0.0.1:8686"

# Host-level logs
[sources.sql_log]
type = "file"
include = ["/tmp/sql.log"]

# Host-level metrics (cpu, memory, disk, etc)
#[sources.host_metrics]
#type = "host_metrics"

# Vector's own internal metrics
#[sources.internal_metrics]
#type = "internal_metrics"


# --> Add transforms here to parse, enrich, and process data
[transforms.sql_log_grok]
type = "grok_parser"
inputs = ["sql_log"]
pattern = "\"%{GREEDYDATA:app_name}\",\"%{WORD:app_trace_id}\",\"%{WORD:sql_trace_id}\",\"%{GREEDYDATA:time}\",\"%{IPV4:db_host}\",\"%{HOSTNAME:exec_host}\",\"%{NUMBER:exec_time}\",\"%{INT:pid}\",\"%{GREEDYDATA:php_sapi}\",\"%{URIPATHPARAM:request_uri}\",\"%{GREEDYDATA:referer}\",\"%{WORD:md5}\",\"%{GREEDYDATA:trace_sql}\",\"%{GREEDYDATA:trace_sql_binds}\""

[transforms.sql_log_clickhouse]
type = "remap"
inputs = ["sql_log_grok"]
source = '''
  . = {
    "timestamp": .time,
    "app_name": .app_name,
    "app_trace_id": .app_trace_id,
    "sql_trace_id": .sql_trace_id,
    "db_host": .db_host,
    "exec_host": .exec_host,
    "exec_time": to_float!(.exec_time),
    "pid": to_int!(.pid),
    "php_sapi": .php_sapi,
    "request_uri": .request_uri,
    "referer": .referer,
    "trace_sql_md5": .md5,
    "trace_sql": .trace_sql,
    "trace_sql_binds": .trace_sql_binds
  }
  '''

# print all events, replace this with your desired sink(s)
# https://vector.dev/docs/reference/sinks/
[sinks.sql_log_out]
type = "console"
inputs = ["sql_log_clickhouse"]
encoding.codec = "json"

#[sinks.out_file]
#type = "file"
#inputs = [ "logs" ]
#path = "/tmp/vector.log"
#encoding.codec = "json"

[sinks.sql_log_clickhouse_sink]
type = "clickhouse" # required
inputs = ["sql_log_clickhouse"] # required
compression = "gzip" # optional, default
database = "deli_com" # optional, no default
endpoint = "http://localhost:18123" # required
table = "trace_sql" # required
